### ISSUE TITLE
Set modifiers in the construct

### ISSUE THREAD

**Issue by apalfrey** [stgdp/fancy-logger#4]
Request was made after some feedback for the modifiers to be set when initialising the logger.

Something like this should work:
```javascript
logger( {
    modifiers: {
        fg: "red",
        bg: "white",
        bright: {
            fg: true,
            bg: false
        },
        decoration: {
            bold: true,
            dim: false,
            italic: false,
            underline: false,
            inverse: false,
            hidden: false,
            strike: false,
            frame: false,
            encircle: false,
            overline: false
        }
    }
} )
```

**NOTE:** `false` values won't need to be sent, and are just there to show the full availability

**Comment by luc122c** [comment]
To make things a bit simpler, perhaps `decoration` could be an array? For example, `decoration: ['bold','strike']`? The only improvement this offers is not having to write 'true' over and over.

**Comment by apalfrey** [comment]
@luc122c I might be able to implement both of them side-by-side, so you can use either for the same result? It would give a further amount of flexibility to the user...

**Comment by luc122c** [comment]
@apalfrey Yeah, that would be good.

**Comment by apalfrey** [comment]
@luc122c Cool, I'll go ahead and get that coded up and tested tomorrow and publish a beta. From there it should just be minor tweaks and bug fixes before a full release

**Comment by apalfrey** [comment]
@luc122c This has been completed in v1.0.0-beta.4. Link below for published npm package

https://www.npmjs.com/package/@stgdp/fancy-logger/v/1.0.0-beta.4
